baseurl: /reis-mahnic

collections:
  games:
    output: true
  software:
    output: true
    
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "games"
    values:
      layout: "subpage"
  - scope:
      path: ""
      type: "software"
    values:
      layout: "subpage"

sass:
  sass_dir: assets/css
  style: compressed

plugins:
- jekyll-autoprefixer
  