backend:
  name: test-repo

media_folder: media_folder

collections:
  - name: games
    label: Games
    folder: _games
    create: true
    fields:
      - {name: title, label: Title, widget: string}
      - {name: release_date, label: Release Year, widget: date, format: 'YYYY' }
      - {name: header_image, label: Header Image, widget: image}
      - {name: body, label: Content, widget: markdown}

